---

- name: Get microk8s status
  command: /snap/bin/microk8s.status --wait-ready
  changed_when: false
  register: microk8s_status
  tags: [ config, microk8s ]

- name: Enable microk8s dashboard addon
  command: /snap/bin/microk8s.enable dashboard
  when: "'dashboard: enabled' not in microk8s_status.stdout_lines"
  tags: [ config, microk8s ]

- name: Enable microk8s dns addon
  command: /snap/bin/microk8s.enable dns
  when: "'dns: enabled' not in microk8s_status.stdout_lines"
  tags: [ config, microk8s ]

- name: Enable microk8s registry addon
  command: /snap/bin/microk8s.enable registry
  when: "'registry: enabled' not in microk8s_status.stdout_lines"
  tags: [ config, microk8s ]

- name: Enable microk8s storage addon
  command: /snap/bin/microk8s.enable storage
  when: "'storage: enabled' not in microk8s_status.stdout_lines"
  tags: [ config, microk8s ]