---
  - hosts: all
    become: true
    gather_facts: no
    vars:
      ansible_python_interpreter: auto_silent
      docker_version: "5:19.03.5~3-0~raspbian-buster"
    tasks:

      # Make sure python 3 is installed before doing anything.
      - name: Install Python
        raw: command -v python3 || { apt-get update && apt-get install -y python3 python3-apt; }
        changed_when: false
        tags: [ always, install ]

      # Gather ansible facts (requires python).
      # (Facts are required for many Ansible modules to work correctly.)
      - name: Gather facts
        setup:
        tags: [ always ]

      - name: Set hostname
        hostname:
          name: "{{ hostname }}"
        tags: [ config ]

      - name: Set hostname in /etc/hosts
        lineinfile:
          path: /etc/hosts
          regexp: "^127.0.1.1[ \t]"
          line: "127.0.1.1 {{ hostname }}"
        tags: [ config ]

      - name: Install pip
        apt:
          name: python3-pip
          state: present
        tags: [ install, pip ]

      - name: Get architecture
        command: dpkg --print-architecture
        changed_when: false
        register: architecture

      - name: Install tools
        apt:
          name:
            - apt-transport-https
            - ca-certificates
            - curl
            - gpg
        tags: [ install ]

      - name: Add Docker apt key
        apt_key:
          url: https://download.docker.com/linux/raspbian/gpg
          state: present
        tags: [ docker, install ]

      - name: Add Docker apt repository
        apt_repository:
          repo: deb [arch={{ architecture.stdout }}] https://download.docker.com/linux/raspbian {{ ansible_distribution_release }} stable
          state: present
        tags: [ docker, install ]

      - name: Install Docker
        apt:
          name: docker-ce={{ docker_version }}
          install_recommends: no
          update_cache: yes
          state: present
        tags: [ docker, install ]

      - name: Install docker-compose
        pip:
          name: docker-compose
        tags: [ docker, install ]

      - name: Create .config directory
        file:
          path: /home/pi/.config
          owner: pi
          group: pi
          mode: 0700
          state: directory

      - name: Create htop configuration directory
        file:
          path: /home/pi/.config/htop
          owner: pi
          group: pi
          mode: 0700
          state: directory

      - name: Configure htop
        template:
          src: htop
          dest: /home/pi/.config/htop/htoprc
          owner: pi
          group: pi
          mode: 0644