---

- name: Install nginx
  apt:
    name: nginx={{ nginx_apt_version }}
    state: present
    update_cache: true
  tags: [ rp, install ]

- name: Start nginx
  service:
    name: nginx
    state: started
  tags: [ rp, install ]

- name: Configure nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx
  tags: [ rp, config ]