---

- name: Check if node is part of a cluster
  command: /snap/bin/microk8s.status --wait-ready
  changed_when: false
  register: microk8s_status_result

- name: Get join node command from master
  command: /snap/bin/microk8s.add-node
  delegate_to: "{{ k8s_master_host }}"
  delegate_facts: true
  register: add_node_result
  when: "'in a cluster' not in microk8s_status_result.stdout"

- name: Join microk8s master
  command: "{{ add_node_result.stdout_lines | select('match', '^.*' + (k8s_master_host_address | quote) + ':') | first | trim | regex_replace('^.*\\s?microk8s.join', '/snap/bin/microk8s.join') }}"
  when: "'in a cluster' not in microk8s_status_result.stdout"

- name: List nodes from the microk8s master
  command: /snap/bin/microk8s.kubectl get nodes
  changed_when: false
  delegate_to: "{{ k8s_master_host }}"
  delegate_facts: true
  run_once: true