version: '3.7'

services:

  locust:
    build: .
    environment:
      TARGET_URL: "http://api:5000"
    image: boardr/locust
    ports:
      - "8089:8089"

  api:
    image: boardr/server
    build: ../server
    depends_on:
      - db
    environment:
      BOARDR_BASE_URL: http://api:5000
      BOARDR_DATABASE_URL: ecto://boardr:changeme@db/boardr
      BOARDR_PORT: 5000
      BOARDR_SECRET: changeme
    networks:
      - db
      - default
    ports:
      - "${SSH_PORT:-2222}:22"
      - "${PORT:-5000}:5000"
    volumes:
      - "./tmp/id_rsa:/etc/boardr/id_rsa:ro"

  db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: boardr
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: boardr
    networks:
      - db
    volumes:
      - "db_data:/var/lib/postgresql/data"

networks:
  db:

volumes:
  db_data: