version: '3.7'

services:

  locust:
    build: .
    depends_on:
      - rp
    environment:
      TARGET_URL: "http://boardr"
    image: boardr/locust
    ports:
      - "8089:8089"

  rp:
    image: nginx:1.17.8-alpine
    depends_on:
      - api
    networks:
      default:
        aliases:
          - boardr
      web:
    ports:
      - "${PORT:-5000}:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"

  # FIXME: frontend does not work due to API redirecting to http://boardr
  frontend:
    image: boardr/client
    build:
      context: ../client
      args:
        BOARDR_API_URL: http://localhost:${PORT:-5000}/api
    depends_on:
      - api
    networks:
      - web

  api:
    image: boardr/server
    build: ../server
    depends_on:
      - db
    environment:
      BOARDR_BASE_URL: http://boardr
      BOARDR_DATABASE_URL: ecto://boardr:changeme@db/boardr
      BOARDR_SECRET: changeme
    networks:
      - db
      - web
    ports:
      - "${SSH_PORT:-2222}:22"

  db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: boardr
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: boardr
    networks:
      - db
    volumes:
      - "db_data:/var/lib/postgresql/data"

networks:
  db:
  web:

volumes:
  db_data:
