version: '3.7'

x-worker: &worker
  image: boardr/worker
  build:
    context: ../server
    dockerfile: Dockerfile.worker
  depends_on:
    - db

x-worker-environment: &worker-environment
  BOARDR_BASE_URL: http://boardr
  BOARDR_DATABASE_URL: ecto://boardr:changeme@db/boardr
  BOARDR_LOG_LEVEL: INFO
  BOARDR_SECRET: changeme
  RELEASE_COOKIE: changeme

x-worker-networks: &worker-networks
  db:

services:

  locust:
    build: .
    depends_on:
      - rp
    environment:
      TARGET_URL: "http://boardr"
    image: boardr/locust
    ports:
      - "8089:8089"

  rp:
    image: nginx:1.17.8-alpine
    depends_on:
      - api
    networks:
      default:
        aliases:
          - boardr
      web:
    ports:
      - "${PORT:-5000}:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"

  # FIXME: frontend does not work due to API redirecting to http://boardr
  frontend:
    image: boardr/client
    build:
      context: ../client
      args:
        BOARDR_API_URL: http://localhost:${PORT:-5000}/api
    depends_on:
      - api
    networks:
      - web

  api:
    image: boardr/server
    build: ../server
    depends_on:
      - db
    environment:
      BOARDR_BASE_URL: http://boardr
      BOARDR_DATABASE_URL: ecto://boardr:changeme@db/boardr
      BOARDR_EPMD_HOSTS: boardr@172.28.1.2,boardr@172.28.1.3,boardr@172.28.1.4
      # BOARDR_EPMD_HOSTS: boardr@172.28.1.1,boardr@172.28.1.2,boardr@172.28.1.3,boardr@172.28.1.4
      BOARDR_LOG_LEVEL: INFO
      BOARDR_RELEASE_NODE_ADDRESS: 172.28.1.1
      BOARDR_RELEASE_NODE_NAME: boardr
      BOARDR_SECRET: changeme
      # BOARDR_SWARM_NODE_BLACKLIST: boardr@172.28.1.1
      # BOARDR_SWARM_NODE_WHITELIST: boardr@172.28.1.2,boardr@172.28.1.3,boardr@172.28.1.4
      RELEASE_COOKIE: changeme
    networks:
      db:
      web:
      workers:
        ipv4_address: 172.28.1.1
    ports:
      - "${SSH_PORT:-2222}:22"

  worker1:
    <<: *worker
    environment:
      <<: *worker-environment
      # BOARDR_EPMD_HOSTS: boardr@172.28.1.1,boardr@172.28.1.3,boardr@172.28.1.4
      # BOARDR_EPMD_HOSTS: boardr@172.28.1.1,boardr@172.28.1.2,boardr@172.28.1.3,boardr@172.28.1.4
      BOARDR_RELEASE_NODE_ADDRESS: 172.28.1.2
      # BOARDR_SWARM_NODE_BLACKLIST: boardr@172.28.1.1
      # BOARDR_SWARM_NODE_WHITELIST: boardr@172.28.1.2,boardr@172.28.1.3,boardr@172.28.1.4
    networks:
      <<: *worker-networks
      workers:
        ipv4_address: 172.28.1.2

  worker2:
    <<: *worker
    environment:
      <<: *worker-environment
      # BOARDR_EPMD_HOSTS: boardr@172.28.1.1,boardr@172.28.1.2,boardr@172.28.1.4
      # BOARDR_EPMD_HOSTS: boardr@172.28.1.1,boardr@172.28.1.2,boardr@172.28.1.3,boardr@172.28.1.4
      BOARDR_RELEASE_NODE_ADDRESS: 172.28.1.3
      # BOARDR_SWARM_NODE_BLACKLIST: boardr@172.28.1.1
      # BOARDR_SWARM_NODE_WHITELIST: boardr@172.28.1.2,boardr@172.28.1.3,boardr@172.28.1.4
    networks:
      <<: *worker-networks
      workers:
        ipv4_address: 172.28.1.3

  worker3:
    <<: *worker
    environment:
      <<: *worker-environment
      # BOARDR_EPMD_HOSTS: boardr@172.28.1.1,boardr@172.28.1.2,boardr@172.28.1.3
      # BOARDR_EPMD_HOSTS: boardr@172.28.1.1,boardr@172.28.1.2,boardr@172.28.1.3,boardr@172.28.1.4
      BOARDR_RELEASE_NODE_ADDRESS: 172.28.1.4
      # BOARDR_SWARM_NODE_BLACKLIST: boardr@172.28.1.1
      # BOARDR_SWARM_NODE_WHITELIST: boardr@172.28.1.2,boardr@172.28.1.3,boardr@172.28.1.4
    networks:
      <<: *worker-networks
      workers:
        ipv4_address: 172.28.1.4

  db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: boardr
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: boardr
    networks:
      - db
    volumes:
      - "db_data:/var/lib/postgresql/data"

networks:
  db:
  web:
  workers:
    ipam:
      driver: default
      config:
          - subnet: 172.28.0.0/16

volumes:
  db_data:
