---
- hosts: all
  become: true
  vars:
    dns_nameservers:
      - 8.8.8.8
      - 8.8.4.4
    docker_version: 5:19.03.5~3-0~ubuntu-bionic

  handlers:

    - name: Restart Docker daemon
      service:
        name: docker
        state: restarted
      tags: [ docker ]

  tasks:

    - name: Add entries to /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^192.168.50.4 {{ item }}'
        line: '192.168.50.4 {{ item }}'
        owner: root
        group: root
        mode: 0644
        state: present
      with_items:
        - boardr.vagrant
        - locust.boardr.vagrant
        - traefik.boardr.vagrant
      tags: [ config ]

    - name: Install tools
      apt:
        name:
          # Unless specified, those are the requirements to install Docker.
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - python3-pip # To install docker-py.
          - resolvconf # For DNS nameserver configuration.
          - software-properties-common
        state: present
        update_cache: true
      tags: [ install ]

    - name: Enable & start resolvconf
      service:
        name: resolvconf
        enabled: true
        state: started
      tags: [ dns, install ]

    - name: Configure resolvconf head file
      template:
        src: resolvconf-head
        dest: /etc/resolvconf/resolv.conf.d/head
      register: dns_resolvconf_head_template
      tags: [ dns, config ]

    - name: Enable & start resolvconf
      service:
        name: resolvconf
        state: restarted
      when: dns_resolvconf_head_template is changed
      tags: [ dns, config ]

    - name: Add Docker apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: [ docker, install ]

    - name: Add Docker apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      tags: [ docker, install ]

    - name: Install Docker
      apt:
        name: docker-ce={{ docker_version }}
        update_cache: yes
        state: present
      tags: [ docker, install ]

    - name: Configure Docker daemon
      template:
        src: docker-daemon.json
        dest: /etc/docker/daemon.json
      notify: Restart Docker daemon
      tags: [ docker, config ]

    - name: Install docker-py
      pip:
        name: docker-py
      tags: [ docker, install ]

    - name: Install microk8s
      snap:
        name: microk8s
        classic: true
        state: present
      tags: [ microk8s, install ]

    - name: Add the root user to the microk8s group
      user:
        name: root
        append: true
        groups: microk8s
      tags: [ microk8s, config ]

    - name: Alias microk8s.kubectl to kubectl
      lineinfile:
        create: true
        path: /root/.bash_profile
        regexp: '^alias kubectl='
        line: 'alias kubectl="microk8s.kubectl"'
        owner: root
        group: root
        mode: 0600
        state: present
      tags: [ microk8s, config ]

    - name: Get microk8s status
      command: /snap/bin/microk8s.status --wait-ready
      changed_when: false
      register: microk8s_status_result
      tags: [ microk8s, config ]

    - name: Enable the microk8s dashboard addon
      command: /snap/bin/microk8s.enable dashboard
      register: enable_microk8s_dashboard_result
      changed_when: "'created' in enable_microk8s_dashboard_result.stdout"
      when: "'dashboard: enabled' not in microk8s_status_result.stdout_lines"
      tags: [ microk8s, config ]

    - name: Enable the microk8s dns addon
      command: /snap/bin/microk8s.enable dns
      register: enable_microk8s_dns_result
      changed_when: "'created' in enable_microk8s_dns_result.stdout"
      when: "'dns: enabled' not in microk8s_status_result.stdout_lines"
      tags: [ microk8s, config ]

    - name: Enable the microk8s registry addon
      command: /snap/bin/microk8s.enable registry
      register: enable_microk8s_registry_result
      changed_when: "'created' in enable_microk8s_registry_result.stdout"
      when: "'registry: enabled' not in microk8s_status_result.stdout_lines"
      tags: [ microk8s, config ]

    - name: Wait for the Docker registry to start
      wait_for:
        host: 127.0.0.1
        port: 32000
      tags: [ microk8s, config ]

    - name: Checkout clean version of repository
      git:
        repo: 'file:///vagrant'
        dest: /srv/checkout
        version: master
      tags: [ build ]

    - name: Build API Docker image
      docker_image:
        name: 127.0.0.1:32000/boardr-api
        build:
          path: /srv/checkout/server
          pull: no
        force_source: yes
        force_tag: yes
        source: build
        state: present
        tag: 0.1.0
        push: yes
      tags: [ build ]

    - name: Build worker Docker image
      docker_image:
        name: 127.0.0.1:32000/boardr-worker
        build:
          path: /srv/checkout/server
          dockerfile: Dockerfile.worker
          pull: no
        force_source: yes
        force_tag: yes
        source: build
        state: present
        tag: 0.1.0
        push: yes
      tags: [ build ]

    - name: Build load testing Docker image
      docker_image:
        name: 127.0.0.1:32000/boardr-load-testing
        build:
          path: /srv/checkout/load-testing
          pull: no
        force_source: yes
        force_tag: yes
        source: build
        state: present
        tag: 0.1.0
        push: yes
      tags: [ build ]

    # - name: Deploy application
    #   command: microk8s.kubectl apply -f /vagrant/k8s.yml
    #   tags: [ demo ]