---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  externalIPs:
    - 10.0.1.200
    - 10.0.1.201
    - 10.0.1.202
    - 10.0.1.203
    - 10.0.1.204
    - 10.0.1.205
    - 10.0.1.206
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 8000
    - protocol: TCP
      name: admin
      port: 8080
  selector:
    app: traefik
  type: NodePort

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: traefik
          image: traefik:v2.0
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.web.Address=:8000
            - --providers.kubernetescrd
          ports:
            - name: web
              containerPort: 8000
            - name: admin
              containerPort: 8080
      nodeSelector:
        type: web