version: '3.7'

services:

  locust:
    build: ../load-testing
    environment:
      TARGET_URL: "http://${TARGET_HOST:-boardr.cluster.vagrant}"
    extra_hosts:
      - "${TARGET_HOST:-boardr.cluster.vagrant}:${TARGET_IP:-192.168.50.5}"
    image: boardr/locust
    ports:
      - "8090:8089"