---

# Reverse proxy server
# ====================
- hosts: rp
  become: true
  vars_files:
    - variables.common.yml
    - [ variables.local.yml, variables.default.yml ]
  roles:
    - role: server
    - role: rp

# Database server
# ===============
- hosts: db
  become: true
  vars_files:
    - variables.common.yml
    - [ variables.local.yml, variables.default.yml ]
  roles:
    - role: server
    - role: db

# API server
# ==========
- hosts: api
  become: true

  vars_files:
    - variables.common.yml
    - [ variables.local.yml, variables.default.yml ]
  roles:
    - role: server
    - role: user
      user_name: boardr
    - role: ssh-known-hosts
      ssh_known_hosts_user: boardr
    - role: ssh-key
      ssh_key_user: boardr
    - role: boardr-release
      boardr_release_name: boardr_api
      boardr_release_user: boardr
    - role: boardr-release
      boardr_release_name: boardr
      boardr_release_user: boardr
    - role: boardr-release-copy
      boardr_release_copy_src: /home/boardr/repo/server/_build/prod/rel/boardr_api/
      boardr_release_copy_dest: /srv/boardr_api/
      boardr_release_copy_user: boardr
    - role: boardr-release-config
      boardr_release_config_user: boardr
    - role: boardr-release-deploy
      boardr_release_deploy_migrate: true
      boardr_release_deploy_serve: true
      boardr_release_deploy_user: boardr
  tasks:
    - name: Copy asdf global versions from boardr repo
      copy:
        src: "/home/boardr/repo/.tool-versions"
        dest: /home/boardr/.tool-versions
        remote_src: true
      become_user: boardr

# Worker servers
# ==============
- hosts: workers
  become: true
  vars_files:
    - variables.common.yml
    - [ variables.local.yml, variables.default.yml ]
  roles:
    - role: server
    - role: user
      user_name: boardr
    - role: boardr-release-copy
      boardr_release_copy_src: /home/boardr/repo/server/_build/prod/rel/boardr/
      boardr_release_copy_dest: /srv/boardr/
      boardr_release_copy_build_server: api
      boardr_release_copy_build_server_public_key_file: /home/boardr/.ssh/id_ed25519.pub
      boardr_release_copy_user: boardr
    - role: boardr-release-config
      boardr_release_config_user: boardr
      boardr_release_config_server: api
    - role: boardr-release-deploy
      boardr_release_deploy_name: boardr
      boardr_release_deploy_service_name: Boardr Worker
      boardr_release_deploy_user: boardr