version: '3.7'

services:
  db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: boardr
      POSTGRES_PASSWORD: {{ db_password }}
      POSTGRES_USER: boardr
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  db_data: