# Boardr database service
---
apiVersion: v1
kind: Service
metadata:
  name: boardr-db
spec:
  type: ClusterIP
  ports:
    - port: &port 5432
      targetPort: *port
  selector:
    app.kubernetes.io/component: db
    app.kubernetes.io/part-of: boardr
    app.kubernetes.io/instance: boardr-vagrant

# Boardr database deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardr-db
spec:
  replicas: 1
  selector:
    matchLabels: &boardr-db-labels
      app.kubernetes.io/component: db
      app.kubernetes.io/part-of: boardr
      app.kubernetes.io/instance: boardr-vagrant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/version: "12.1"
        <<: *boardr-db-labels
    spec:
      containers:
        - name: postgres
          image: postgres:12.1-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: boardr
            - name: POSTGRES_USER
              value: boardr
            - name: POSTGRES_PASSWORD
              value: changeme