---

- name: Create SSH directory
  file:
    path: "{{ ssh_known_hosts_user_ssh_directory }}"
    owner: "{{ ssh_known_hosts_user }}"
    group: "{{ ssh_known_hosts_group }}"
    mode: 0700
    state: directory

- name: Preconfigure SSH known hosts
  known_hosts:
    path: "{{ ssh_known_hosts_file }}"
    name: "{{ item.name }}"
    key: "{{ item.key }}"
  become_user: "{{ ssh_known_hosts_user }}"
  with_items: "{{ ssh_known_hosts }}"