---

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  tags: [ config, server ]

- name: Add hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "^127\\.0\\.0\\.1\\s+{{ inventory_hostname | regex_escape }}$"
    line: "127.0.0.1 {{ inventory_hostname }}"
  tags: [ config, server ]