---

- name: Create boardr config directory
  file:
    path: "{{ boardr_release_config_directory }}"
    owner: "{{ boardr_release_config_user }}"
    group: "{{ boardr_release_config_group }}"
    mode: 0700
    state: directory
  tags: [ boardr-release-config, config ]

- name: Create boardr environment file
  template:
    src: .env
    dest: "{{ boardr_release_config_environment_file }}"
    owner: "{{ boardr_release_config_user }}"
    group: "{{ boardr_release_config_group }}"
    mode: 0600
  tags: [ boardr-release-config, config ]