---

- name: Create .config directory
  file:
    path: /home/ubuntu/.config
    owner: ubuntu
    group: ubuntu
    mode: 0700
    state: directory
  tags: [ config, htop ]

- name: Create htop configuration directory
  file:
    path: /home/ubuntu/.config/htop
    owner: ubuntu
    group: ubuntu
    mode: 0700
    state: directory
  tags: [ config, htop ]

- name: Configure htop
  template:
    src: htoprc
    dest: /home/ubuntu/.config/htop/htoprc
    owner: ubuntu
    group: ubuntu
    mode: 0644
  tags: [ config, htop ]