---

- name: Install snap
  apt:
    name: snapd
    state: present
  register: install_snap_result
  tags: [ snap, install ]

- name: Reboot after installing snap
  reboot:
  when: install_snap_result is changed
  tags: [ snap, install ]