---

- name: Install tools
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - python3-pip
      - software-properties-common
    state: present
    update_cache: true
  tags: [ docker, install ]

- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: [ docker, install ]

- name: Add Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
  tags: [ docker, install ]

- name: Install Docker
  apt:
    name: docker-ce={{ docker_apt_version }}
    update_cache: yes
    state: present
  tags: [ docker, install ]

- name: Install docker-py
  pip:
    name: docker-py
  tags: [ docker, install ]

- name: Configure Docker daemon
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: Restart Docker daemon
  tags: [ docker, config ]

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755