---

- name: Install tools
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: true
  tags: [ docker, install ]

- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: [ docker, install ]

- name: Add Docker apt repository
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu disco stable
    state: present
  tags: [ docker, install ]

- name: Install Docker
  apt:
    name: docker-ce={{ docker_apt_version }}
    update_cache: yes
    state: present
  tags: [ docker, install ]